use tauri::{ipc::Invoke, Wry};

pub(crate) mod bridge;
pub(crate) mod context_menu;
pub(crate) mod install;
pub(crate) mod skills;
pub(crate) mod workspace_grid;
pub(crate) mod workspace_import;

pub(crate) fn invoke_handler() -> impl Fn(Invoke<Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // runtime
        super::get_app_status,
        super::get_workspace_embed_url,
        super::retry_start_backend,
        super::restart_backend_runtime_only,
        super::report_loading_rendered,
        super::notify_frontend_ready,
        super::get_startup_monitor_status,
        super::complete_startup_monitor_route,
        super::submit_prefill,
        super::recover_main_window_boot,
        super::quit_app_gracefully,
        super::get_main_window_close_behavior,
        super::save_main_window_close_behavior,
        super::get_workspace_web_settings,
        super::save_workspace_web_settings,
        super::fallback_workspace_web_to_official,
        super::mark_enhanced_web_ready,
        super::submit_main_window_close_decision,
        super::save_kimi_path,
        super::save_work_dir,
        // workspace grid
        workspace_grid::grid_list_sessions,
        workspace_grid::grid_create_session,
        // bridge
        bridge::get_bridge_settings,
        bridge::save_bridge_settings,
        bridge::delete_bridge_connector,
        bridge::save_bridge_onboarding_config,
        bridge::get_bridge_status,
        bridge::start_bridge,
        bridge::stop_bridge,
        bridge::restart_bridge,
        bridge::list_bridge_bindings,
        bridge::list_bridge_sessions,
        bridge::clear_bridge_binding,
        bridge::reset_bridge_binding_session,
        bridge::reset_bridge_binding_to_default_work_dir,
        bridge::list_bridge_approvals,
        bridge::resolve_bridge_approval,
        bridge::import_bridge_session,
        bridge::get_bridge_log_tail,
        bridge::get_bridge_secrets_mask_view,
        bridge::save_bridge_connector_secrets,
        bridge::start_feishu_connector_onboarding,
        bridge::get_feishu_connector_onboarding_status,
        bridge::cancel_feishu_connector_onboarding,
        bridge::start_weixin_connector_onboarding,
        bridge::get_weixin_connector_onboarding_status,
        bridge::cancel_weixin_connector_onboarding,
        // skills
        skills::install_skill_from_git,
        skills::import_skill_from_path,
        skills::scan_discoverable_skills,
        skills::list_skill_discovery_workspaces,
        skills::list_workspace_skill_targets,
        skills::get_workspace_skill_inventory,
        skills::add_installed_skill_to_workspace_target,
        skills::remove_workspace_target_skill,
        skills::get_discovered_skill_detail,
        skills::import_discovered_skill,
        skills::list_installed_skills,
        skills::get_skill_detail,
        skills::list_skill_file_entries,
        skills::read_skill_file,
        skills::get_skill_usage_stats,
        skills::list_discovered_skill_file_entries,
        skills::read_discovered_skill_file,
        skills::set_skill_trust,
        skills::apply_skill,
        skills::remove_skill,
        skills::list_active_session_skills,
        skills::list_global_skills,
        skills::list_workspace_recent_skills,
        skills::get_workspace_skill_profile,
        skills::set_workspace_skill_pin,
        skills::get_workspace_skill_recommendations,
        skills::update_skill,
        skills::uninstall_skill,
        skills::cleanup_session_skill_projections,
        // workspace hub
        super::workspaces::workspace_list,
        super::workspaces::workspace_register,
        super::workspaces::workspace_register_many,
        super::workspaces::workspace_mark_opened,
        super::workspaces::workspace_remove,
        // harness
        super::harness::harness_list,
        super::harness::harness_get,
        super::harness::harness_dry_run,
        super::harness::list_harness_file_entries,
        super::harness::read_harness_file,
        super::harness::harness_create,
        // scheduler
        super::scheduler::schedule_list,
        super::scheduler::schedule_set_heartbeat,
        super::scheduler::schedule_create_task,
        super::scheduler::schedule_update_task,
        super::scheduler::schedule_delete_task,
        super::scheduler::schedule_run_now,
        super::scheduler::schedule_list_runs,
        // diagnostics
        super::get_diagnostics,
        super::open_logs_folder,
        super::open_external_url,
        super::open_folder,
        super::open_kimi_config_dir,
        super::load_kimi_code_access_config,
        super::save_kimi_code_access_config,
        super::test_kimi_code_access_config,
        super::run_kimi_doctor,
        // install
        install::register_install_session_channel,
        install::get_install_flow_catalog,
        install::get_install_session_snapshot,
        install::start_install_task,
        install::cancel_install_task,
        install::get_install_probe_status,
        install::get_install_settings,
        install::save_install_settings,
        install::get_install_mirror_health_report,
        install::get_powershell_preflight,
        // install compat
        install::install_kimi_dependencies,
        install::install_kimi_code,
        install::upgrade_kimi_code,
        install::uninstall_kimi_code,
        install::install_nodejs,
        // context menu
        context_menu::get_context_menu_status,
        context_menu::enable_context_menu,
        context_menu::disable_context_menu,
        context_menu::save_context_menu_labels,
        // workspace import
        workspace_import::list_workspace_import_targets,
        workspace_import::get_active_workspace_import_request,
        workspace_import::complete_workspace_import_request,
        workspace_import::cancel_workspace_import_request,
        // onboarding/auth
        super::get_onboarding_status,
        super::complete_onboarding,
        super::skip_onboarding,
        super::ack_api_config_step,
        super::start_kimi_code_auth,
        super::refresh_kimi_code_auth,
        super::logout_kimi_code_auth
    ]
}
